<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerChbf9lq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerChbf9lq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerChbf9lq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerChbf9lq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerChbf9lq\appDevDebugProjectContainer();
